name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Restore Dependencies
        run: mvn dependency:resolve

      - name: Build with Maven
        run: mvn clean package

      - name: List Target Directory
        run: ls -l target/

      - name: Find and Run JAR
        run: |
          JAR_FILE=$(ls target/*.jar | head -n 1)
          echo "Running $JAR_FILE"
          java -jar $JAR_FILE
